server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@payrollcore.7dtrjt4.mongodb.net/?appName=payrollcore
      database: auth-db

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-expiration: 604800000